In [1]:
# Scrape KenPom
# https://kenpom.com/index.php?y=2008
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

season = np.arange(2008,2023,1)
season = season[(season ==2022)]
allkp = pd.read_csv('../data/A3_kenpom.csv')
allkp = allkp[allkp['Year']<=2021]
for y in season:
    url = f'https://kenpom.com/index.php?y={y}'
    data = requests.get(url).text
    soup = BeautifulSoup(data, 'html.parser')
    table = soup.find('table', class_=None)
    
    for row in table.tbody.find_all('tr'):    
        # Find all data for each column
        columns = row.find_all('td')
        
        if(columns != []):
            
            Team = columns[1].text.strip()
            Conf = columns[2].text.strip()
            
            AdjEM = columns[4].text.strip()
            AdjO = columns[5].text.strip()
            AdjD = columns[7].text.strip()
            AdjT = columns[9].text.strip()
            SOSEM = columns[13].text.strip()
            SOSO = columns[15].text.strip()
            SOSD = columns[17].text.strip()

            allkp = allkp.append({'Year':y,'Team': Team,'Conf':Conf,'AdjEM':AdjEM,'AdjO':AdjO,'AdjD':AdjD,'AdjT':AdjT,'SOSEM':SOSEM,'SOSO':SOSO,'SOSD':SOSD}, ignore_index=True)
            allkp['Team'] = allkp['Team'].str.replace('\d+','').str.rstrip()
allkp.to_csv('../data/A3_kenpom.csv',index=False)

C:\Users\harmk\AppData\Local\Temp/ipykernel_14004/3364756476.py:36: FutureWarning: The default value of regex will change from True to False in a future version.
  allkp['Team'] = allkp['Team'].str.replace('\d+','').str.rstrip()

In [2]:
allkp.to_csv('../data/A3_kenpom.csv',index=False)
allkp

,Year,Team,Conf,AdjEM,AdjO,AdjD,AdjT,SOSEM,SOSO,SOSD
0,2008,Kansas,B12,35.21,120.9,85.7,66.8,9.57,109.2,99.6
1,2008,Memphis,CUSA,31.51,118.0,86.5,68.1,5.83,107.0,101.1
2,2008,North Carolina,ACC,30.22,122.1,91.9,72.5,10.18,108.0,97.8
3,2008,UCLA,P10,29.94,118.0,88.1,64.1,10.03,109.3,99.3
4,2008,Wisconsin,B10,26.68,113.5,86.8,61.1,7.35,107.1,99.8
...,...,...,...,...,...,...,...,...,...,...
4849,2022,Arkansas Pine Bluff,SWAC,-22.69,96.2,118.8,67.0,-1.94,100.4,102.3
4850,2022,Mississippi Valley St.,SWAC,-23.53,93.6,117.1,71.1,-5.10,98.6,103.7
4851,2022,Eastern Illinois,OVC,-23.87,83.9,107.8,65.5,-2.01,102.5,104.5
4852,2022,Delaware St.,MEAC,-26.06,86.1,112.1,67.5,-4.89,99.8,104.7
4853,2022,IUPUI,Horz,-30.53,80.4,111.0,62.8,-6.90,100.8,107.7

In [3]:

# Scrape ESPN BPI
# https://www.espn.com/mens-college-basketball/bpi/_/view/bpi/season/2008/page/2
# Importing the required libraries
import requests
import pandas as pd
from bs4 import BeautifulSoup
import numpy as np

season = np.arange(2008,2023,1)
season = season[(season == 2022)]
page = np.arange(1,8,1)

allBPI = pd.read_csv('../data/A3_BPI.csv')
allBPI = allBPI[allBPI['Year']<=2021]
for y in season:
    if y == 2022: page = np.arange(1,9,1)
    for x in page:
        # Downloading contents of the web page
        url = f"https://www.espn.com/mens-college-basketball/bpi/_/view/bpi/season/{y}/page/{x}"
        data = requests.get(url).text

        # Creating BeautifulSoup object
        soup = BeautifulSoup(data, 'html.parser')
        table = soup.find('table', class_='bpi__table')

        # Collecting Ddata
        for row in table.tbody.find_all('tr'):    
            # Find all data for each column
            columns = row.find_all('td')
            
            if(columns != []):
               
                Team = columns[1].find_all('span')[1].text.strip()
               
                BPIO = columns[4].text.strip()
                BPID = columns[5].text.strip()
                
                allBPI = allBPI.append({'Year':y,'Team': Team,'BPIO':BPIO,'BPID':BPID}, ignore_index=True)
allBPI.to_csv('../data/A3_BPI.csv',index=False)

In [4]:
allBPI

      Year                      Team   BPIO   BPID
0     2008                    Kansas   12.4    9.6
1     2008            North Carolina   19.2    1.0
2     2008                   Memphis   11.3    8.0
3     2008                      UCLA    7.9   10.9
4     2008                      Duke   13.8    4.3
...    ...                       ...    ...    ...
4852  2022       Arkansas-Pine Bluff   -6.0   -8.8
4853  2022            Delaware State  -10.7   -4.8
4854  2022          Eastern Illinois  -11.6   -4.2
4855  2022  Mississippi Valley State   -7.8  -10.1
4856  2022                     IUPUI  -14.3   -4.5

[4857 rows x 4 columns]

In [5]:
# Scrape Basketball Reference
# https://www.sports-reference.com/cbb/seasons/2008-ratings.html
# Importing the required libraries
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

season = np.arange(2008,2023,1)
season = season[(season ==2022)]
allBR = pd.read_csv('../data/A3_BR.csv')
allBR = allBR[allBR['Year']<=2021]
for y in season:
    # Downloading contents of the web page
    url = f"https://www.sports-reference.com/cbb/seasons/{y}-ratings.html"
    data = requests.get(url).text

    # Creating BeautifulSoup object
    soup = BeautifulSoup(data, 'html.parser')
    table = soup.find('table', class_='stats_table')

    # Collecting Ddata
    for row in table.tbody.find_all('tr'):    
        # Find all data for each column
        columns = row.find_all('td')
        if(columns != []):
            Team = columns[0].text.strip()
            if y <= 2021:
                W = columns[3].text.strip()
                L = columns[4].text.strip()
                Pts = columns[5].text.strip()
                Opp = columns[6].text.strip()
                MOV = columns[7].text.strip()
                SOS = columns[9].text.strip()
                OSRS = columns[11].text.strip()
                DSRS = columns[12].text.strip()
                SRS = columns[13].text.strip()
            if y > 2021:
                W = int(columns[4].text.strip())
                L = int(columns[5].text.strip())
                Pts = columns[6].text.strip()
                Opp = columns[7].text.strip()
                MOV = columns[8].text.strip()
                SOS = columns[10].text.strip()
                OSRS = columns[12].text.strip()
                DSRS = columns[13].text.strip()
                SRS = columns[14].text.strip()
            allBR = allBR.append({'Year':y,'Team':Team,"W":W,'L':L,'Pts':Pts,'Opp':Opp,'MOV':MOV,'SOS':SOS,'OSRS':OSRS,'DSRS':DSRS,'SRS':SRS},ignore_index=True)
allBR.to_csv('../data/A3_BR.csv',index=False)

In [6]:
allBR

,Year,Team,W,L,Pts,Opp,MOV,SOS,OSRS,DSRS,SRS
0,2008,Kansas,37,3,80.5,61.5,19.03,8.2,14.9,11.99,26.9
1,2008,North Carolina,36,3,88.6,72.5,16.05,8.12,23.41,0.76,24.17
2,2008,Memphis,38,2,79.9,61.9,17.98,5.76,13.46,10.28,23.73
3,2008,UCLA,35,4,73.5,59.0,14.54,7.71,8.6,13.1,21.71
4,2008,Duke,28,6,83.2,69.4,13.79,9.28,16.48,5.04,21.52
...,...,...,...,...,...,...,...,...,...,...,...
4829,2022,Arkansas-Pine Bluff,6,21,64.4,77.4,-13.04,-3.15,-8.07,-11.00,-19.07
4830,2022,Eastern Illinois,5,23,57.0,71.2,-14.18,-3.04,-17.59,-2.15,-19.74
4831,2022,Mississippi Valley State,2,22,66.7,83.9,-17.17,-5.21,-5.08,-17.29,-22.37
4832,2022,IUPUI,3,23,52.6,67.1,-14.46,-5.87,-21.77,-1.27,-23.04
4833,2022,Delaware State,2,21,61.8,73.3,-11.48,-5.98,-14.52,-8.65,-23.18